### ISSUE TITLE
Using DICE with 1.5.7b3 - cannot parse reply

### ISSUE THREAD

**Issue by MaikeruJon** [JRCSTU/CO2MPAS-TA#15]
Hello
According to the latest information from the CO2MPAS team,  I have updated CO2MPAS to 1.5.7b3.
I have a configuration file for E-mail based on the instructions in the May workshop and using a GpgSpec.master_key from that workshop.
I have run CO2MPAS from the GUI and sent and received E-mails.
I tried to parse the reply:

D:\CO2mpas\co2mpas_AIO-v1.5.5\CO2MPAS>co2dice project tparse
15:18:49       : INFO:TparseCmd:Reading STDIN; paste message verbatim!
- -----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iJwEAAEIAAYFAlljE5wACgkQsSTJmcu7Uv94EwP/VSbBwRzuPH9u0K+nFCcVhd/Z
ZyXgz3IKZoneX+60LRVDMiI6fyeMdXXSKhmPalM8O7i8oxJC0uf3CIBhdb/IFu4t
RlnPV1ZEu/4MmJ+KVotwoLxwJAdsFzHWvwrU2niWO3mlIO+oo+4gCeeLlkfsT4sk
UbZJkczUX0QaJyZH7qo=
=/QhT
- -----END PGP SIGNATURE-----
^Z
15:19:04       :ERROR:co2dice:Cannot verify timestamp-response's signature due to: None

Please help.

Thanks

Michael

**Comment by dimitriskomnos** [comment]
Dear Michael,

As written in the DICE instructions, 
you have to copy/paste the message you received starting from: 
``-----BEGIN PGP SIGNED MESSAGE-----`` to the end and not only the last part. 

Can you please try again, and report if you managed to successfully parse the Time stamp response  and get the _DICE decision_?

Thank you in advance and we look forward hearing from you. 
Dimitris.

---

**NOTE:** 
Here is a picture of the structure of a time stamp response, explaining the parts that it consists of. You have to copy/ paste the whole part of this message.  
![e-mail](https://user-images.githubusercontent.com/22169206/28006665-96a20aa0-6550-11e7-863b-b90bac9ee4c7.PNG)

**Comment by MaikeruJon** [comment]
Hello
Many thanks for a quick reply. Sorry for my confusion wrt what should be pasted.
Please see below the latest result and please give me your advice on my next step.
Thank you for your time.

D:\CO2mpas\co2mpas_AIO-v1.5.5\CO2MPAS>co2dice project tparse
16:25:56       : INFO:TparseCmd:Reading STDIN; paste message verbatim!
-----BEGIN PGP SIGNED MESSAGE-----

########################################################
#
# This is a proof of posting certificate from # stamper.itconsult.co.uk certifying that a user # claiming to be:-
#     michael@vca-asia.jp
# requested that this message be sent to:-
#     JRC-CO2MPAS@ec.europa.eu
#     CLIMA-LDV-CO2-CORRELATION@ec.europa.eu
#
# This certificate was issued at 05:45 (GMT) # on Monday 10 July 2017 with reference 0968926 # # CAUTION: while the message may well be from the sender
#          indicated in the "From:" header, the sender
#          has NOT been authenticated by this service
#
# For information about the Stamper service see
#        http://www.itconsult.co.uk/stamper.htm
#
########################################################


object 266fd366ee19e58b6c040cfe7d65017733b6246f
type commit
tag dices/IP-10-AAA-2017-1004/0
tagger michael@vca-asia.jp <michael@vca-asia.jp> 1499665307 +0900

- - {v: 1.0.0, a: drep 2 files, p: IP-10-AAA-2017-1004, s: tagged}
- - file: co2mpas_demo-3.xlsx
  iokind: inp
  report: {report_type: input_report, vehicle_family_id: IP-10-AAA-2017-1004}
- - file: 20170710_131634-co2mpas_demo-3.xlsx
  iokind: out
  report:
    0.vehicle_family_id: [IP-10-AAA-2017-1004, IP-10-AAA-2017-1004]
    1.CO2MPAS_version: [1.5.7.b3, 1.5.7.b3]
    2.report_type: [dice_report, dice_report]
    3.datetime: ['2017/07/10-13:16:50', '2017/07/10-13:16:50']
    4.TA_mode: ['True', 'True']
    5.CO2MPAS_deviation: [0.2817, .nan]
    6.Vehicle: [.nan, .nan]
    7.fuel_type: [diesel, diesel]
    8.engine_capacity: [1128.0, 1128.0]
    9.gear_box_type: [manual, manual]
    10.engine_is_turbo: [1.0, 1.0]
    11.Model_scores WLTP-H: [.nan, .nan]
    12.alternator_model (battery currents): [5.5848, 13.9812]
    13.alternator_model (alternator currents): [5.6787, 16.0966]
    14.at_model: [.nan, .nan]
    15.clutch_torque_converter_model: [0.0687, 0.4813]
    16.co2_params: [0.0027, 0.0013]
    17.engine_cold_start_speed_model: [0.0, 0.4041]
    18.engine_coolant_temperature_model: [0.6719, 0.8102]
    19.engine_speed_model: [0.0, 0.0]
    20.start_stop_model (engine starts): [-0.9922, -0.9922]
    21.start_stop_model (on engine): [-0.9961, -0.9894]
    22.Model_scores WLTP-L: [.nan, .nan]
    23.alternator_model (battery currents): [5.1809, 13.1639]
    24.alternator_model (alternator currents): [5.3944, 15.374]
    25.at_model: [.nan, .nan]
    26.clutch_torque_converter_model: [0.7924, 0.3255]
    27.co2_params: [0.0025, 0.0001]
    28.engine_cold_start_speed_model: [0.0, 0.1755]
    29.engine_coolant_temperature_model: [0.7984, 0.8379]
    30.engine_speed_model: [0.0, 0.0]
    31.start_stop_model (engine starts): [-0.9928, -0.9928]
    32.start_stop_model (on engine): [-0.9872, -0.9867]
- -----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iJwEAAEIAAYFAlljE5wACgkQsSTJmcu7Uv94EwP/VSbBwRzuPH9u0K+nFCcVhd/Z
ZyXgz3IKZoneX+60LRVDMiI6fyeMdXXSKhmPalM8O7i8oxJC0uf3CIBhdb/IFu4t
RlnPV1ZEu/4MmJ+KVotwoLxwJAdsFzHWvwrU2niWO3mlIO+oo+4gCeeLlkfsT4sk
UbZJkczUX0QaJyZH7qo=
=/QhT
- -----END PGP SIGNATURE-----

-----BEGIN PGP SIGNATURE-----
Version: 2.6.3i
Charset: noconv
Comment: Stamper Reference Id: 0968926

iQEVAgUBWWMUXIGVnbVwth+BAQE9vwf9G9mJ5YJ7Eg+Wtk4ULjvmLY1LhF3R9qN5
5d8UuTCShpASxxZ/5bdxUXpdU7e5fr+42WHnyZzUX1EtFlFQbdF828yM5zqC+i3p
ZFyRR0Nuu74DxLK0nB6yvRqbEyNsQpQPKS7Oe7rP13bgp0VNBST3HeGcla5jlXah
uaXkgRnlWryOhOg9PJqW/a3q2FQUENqOEV1AshTKoR0iaEvXfIfsFNCibH61EKDp
6zUXLoOWbt8Yb8ru1bzjCDzl5+sgyPbd+HQc9PXaW/7PIOD92cGCfmZOV4QDV4Se
/4MWG3MNNIAmn8N2SpD7USbKVjnhiL/+jFQgATfd7CFyKVFw/jCJXA==
=3waa
-----END PGP SIGNATURE-----
^Z
16:27:56       :ERROR:co2dice:Cannot verify timestamp-response's signature due to: signature bad

**Comment by dimitriskomnos** [comment]
Dear Michael, 

First of all, I changed your comment above, putting  [```] before and after the pasted message the console,
in order to be easily seen. 

We have received the response from the time stamper that you pasted here, since you have inserted the CO2MPAS email in the `tstamp_recipients`.

Besides this, we managed to parse it and get the decision. 
So probably it can be a matter of your e-mail server.

What I suggest you to try is this:

Go to the time stamp response mail, the one that you copied/ pasted in the console, and try to find the option to open the mail as ``message source``. 

Here for example, the ways to do it in some public email providers:

1. 
![image](https://user-images.githubusercontent.com/22169206/28009054-4752c8e0-655a-11e7-89ac-af37d332142d.png)

2.
![image](https://user-images.githubusercontent.com/22169206/28009070-58122a5e-655a-11e7-9d54-e4bc94bb64ce.png)

3. 
![image](https://user-images.githubusercontent.com/22169206/28009098-730ebfc0-655a-11e7-886f-4bd30fecf2b8.png)

Then, copy the message from there, and paste it in the console, as you did before.

Please reply back if this solves your problem.
Kind regards,
Dimitris

**Comment by MaikeruJon** [comment]
Dear Dimitris

 

Thank you for your prompt reply always.

 

I tried ‘View Source’ as you recommended. But, certainly in Outlook 2010, as the received mail was formatted in plain text, ‘View Source’ is greyed out. When I posted the message to the message window in GitHub, there was HTML formatting automatically, but the original mail did not have any.

 

Anyway, I edited the message by pasting into Notepad and adding the triple apostrophes, according to your kind advice.

 

I then pasted the complete assembly to the CO2MPAS console using Shift+Insert and the end of stream key.

 

I got the below result:

 

 

D:\CO2mpas\co2mpas_AIO-v1.5.5\CO2MPAS>co2dice project tparse

11:47:31       : INFO:TparseCmd:Reading STDIN; paste message verbatim!

'''-----BEGIN PGP SIGNED MESSAGE-----

 

########################################################

#

# This is a proof of posting certificate from # stamper.itconsult.co.uk certifying that a user # claiming to be:-

#     michael@vca-asia.jp

# requested that this message be sent to:-

#     JRC-CO2MPAS@ec.europa.eu

#     CLIMA-LDV-CO2-CORRELATION@ec.europa.eu

#

# This certificate was issued at 05:45 (GMT) # on Monday 10 July 2017 with reference 0968926 # # CAUTION: while the message may well be from the sender

#          indicated in the "From:" header, the sender

#          has NOT been authenticated by this service

#

# For information about the Stamper service see

#        http://www.itconsult.co.uk/stamper.htm

#

########################################################

 

 

object 266fd366ee19e58b6c040cfe7d65017733b6246f

type commit

tag dices/IP-10-AAA-2017-1004/0

tagger michael@vca-asia.jp <michael@vca-asia.jp> 1499665307 +0900

 

- - {v: 1.0.0, a: drep 2 files, p: IP-10-AAA-2017-1004, s: tagged}

- - file: co2mpas_demo-3.xlsx

  iokind: inp

  report: {report_type: input_report, vehicle_family_id: IP-10-AAA-2017-1004}

- - file: 20170710_131634-co2mpas_demo-3.xlsx

  iokind: out

  report:

    0.vehicle_family_id: [IP-10-AAA-2017-1004, IP-10-AAA-2017-1004]

    1.CO2MPAS_version: [1.5.7.b3, 1.5.7.b3]

    2.report_type: [dice_report, dice_report]

    3.datetime: ['2017/07/10-13:16:50', '2017/07/10-13:16:50']

    4.TA_mode: ['True', 'True']

    5.CO2MPAS_deviation: [0.2817, .nan]

    6.Vehicle: [.nan, .nan]

    7.fuel_type: [diesel, diesel]

    8.engine_capacity: [1128.0, 1128.0]

    9.gear_box_type: [manual, manual]

    10.engine_is_turbo: [1.0, 1.0]

    11.Model_scores WLTP-H: [.nan, .nan]

    12.alternator_model (battery currents): [5.5848, 13.9812]

    13.alternator_model (alternator currents): [5.6787, 16.0966]

    14.at_model: [.nan, .nan]

    15.clutch_torque_converter_model: [0.0687, 0.4813]

    16.co2_params: [0.0027, 0.0013]

    17.engine_cold_start_speed_model: [0.0, 0.4041]

    18.engine_coolant_temperature_model: [0.6719, 0.8102]

    19.engine_speed_model: [0.0, 0.0]

    20.start_stop_model (engine starts): [-0.9922, -0.9922]

    21.start_stop_model (on engine): [-0.9961, -0.9894]

    22.Model_scores WLTP-L: [.nan, .nan]

    23.alternator_model (battery currents): [5.1809, 13.1639]

    24.alternator_model (alternator currents): [5.3944, 15.374]

    25.at_model: [.nan, .nan]

    26.clutch_torque_converter_model: [0.7924, 0.3255]

    27.co2_params: [0.0025, 0.0001]

    28.engine_cold_start_speed_model: [0.0, 0.1755]

    29.engine_coolant_temperature_model: [0.7984, 0.8379]

    30.engine_speed_model: [0.0, 0.0]

    31.start_stop_model (engine starts): [-0.9928, -0.9928]

    32.start_stop_model (on engine): [-0.9872, -0.9867]

- -----BEGIN PGP SIGNATURE-----

Version: GnuPG v2

 

iJwEAAEIAAYFAlljE5wACgkQsSTJmcu7Uv94EwP/VSbBwRzuPH9u0K+nFCcVhd/Z

ZyXgz3IKZoneX+60LRVDMiI6fyeMdXXSKhmPalM8O7i8oxJC0uf3CIBhdb/IFu4t

RlnPV1ZEu/4MmJ+KVotwoLxwJAdsFzHWvwrU2niWO3mlIO+oo+4gCeeLlkfsT4sk

UbZJkczUX0QaJyZH7qo=

=/QhT

- -----END PGP SIGNATURE-----

 

-----BEGIN PGP SIGNATURE-----

Version: 2.6.3i

Charset: noconv

Comment: Stamper Reference Id: 0968926

 

iQEVAgUBWWMUXIGVnbVwth+BAQE9vwf9G9mJ5YJ7Eg+Wtk4ULjvmLY1LhF3R9qN5

5d8UuTCShpASxxZ/5bdxUXpdU7e5fr+42WHnyZzUX1EtFlFQbdF828yM5zqC+i3p

ZFyRR0Nuu74DxLK0nB6yvRqbEyNsQpQPKS7Oe7rP13bgp0VNBST3HeGcla5jlXah

uaXkgRnlWryOhOg9PJqW/a3q2FQUENqOEV1AshTKoR0iaEvXfIfsFNCibH61EKDp

6zUXLoOWbt8Yb8ru1bzjCDzl5+sgyPbd+HQc9PXaW/7PIOD92cGCfmZOV4QDV4Se

/4MWG3MNNIAmn8N2SpD7USbKVjnhiL/+jFQgATfd7CFyKVFw/jCJXA==

=3waa

-----END PGP SIGNATURE-----'''

 

 

^Z

11:47:40       :ERROR:co2dice:Cannot verify timestamp-response's signature due to: None

 

 

I checked the project status:

 

D:\CO2mpas\co2mpas_AIO-v1.5.5\CO2MPAS>co2dice project ls

12:04:25       : INFO:LsCmd:Listing all projects...

* IP-10-AAA-2017-1004: mailed

 

Because you wrote “So probably it can be a matter of your e-mail server.”, I wondered if I could send again, with another address in the configuration file, under c.TstampSender.tstamp_recipients. But I guess that if the project has status ‘mailed, then I can’t send another e-mail to timestamp?

 

My configuration file is attached. File extension is temporarily modified. I included the JRC e-mail address as that was the setup instruction from the May workshop. Please advise if this is not OK.

 

Thanks

 

Michael

**Comment by dimitriskomnos** [comment]
Dear Michael,

Since you are in the testing period and you use the demo files for testing the DICE,
you can initialize a new project and try again. 

We did not receive the configuration file. 

In the field `c.TstampSender.tstamp_recipients` you insert the the e-mail addresses of the receivers of the _timestamped-response_.

So, for now, I suggest to insert there more e-mail addresses, for example a personal one (gmail, yahoo, outlook). You will receive there the same timestamped-response, too.
Try to see if you can parse it from there, because probably the e-mail provider you use, distorts the signature. As I told you before, we received the last timestamped-response and we managed to decode it and get the _OK/SAMPLE_ verdict. 

Looking forward to hearing from you.
Regards,
Dimitris.

**Comment by MaikeruJon** [comment]
Hello Dimitris

Thanks for sticking with me on this.
Following your advice I set up a new E-mail account on a different host.
I received these E-mails via Mozilla Thunderbird.
I could then parse the result.
If I have the result below, I believe that I can say that we are now OK for running the CO2MPAS software and using DICE?
Do you agree?

*********************************

17:07:15       : INFO:transitions.core:IP-10-AAA-2017-1009: Exited state mailed
17:07:15       : INFO:transitions.core:IP-10-AAA-2017-1009: Entered state nosample
17:07:15       : INFO:co2mpas.sampling.project.Project:Committing Project(IP-10-AAA-2017-1009: nosample): diced as OK
{decision: OK, hexnum: D9F8D7B8923B63E10CF6FD491DBDCAE59FB19357, percent: 11}

*********************************
I believe that I now have to apply to obtain an 'official' key to replace the key that I obtained for testing at the May workshop?

Please advise / confirm.

Thanks again for your great help.

Best regards

Michael

**Comment by dimitriskomnos** [comment]
Dear Michael, these are great news!
Yes, the verdict looks fine!


Please, do some more tests in order to be sure that everything runs smoothly. 
This time please: 
1. Insert the **official e-mail address** of the official user inside the field for the `c.TstampSender.tstamp_recipients`. This is mandatory, in order for us to be able to recognize from which TA/TS the response from the Time stamper is coming. 
2. Put CLIMA and CO2MPAS addresses, too. 

So in this case we will be able to verify too that the procedure was correct. If I am correct, we did not receive the specific time stamp response. 

Then we will proceed with the instructions for the generation of the official key. 
Keep in mind that:
- you can start the official DICEing from 27th of July, not earlier. So until then, we can make some more test.
- A new release is going to be published soon. So you can test this too. The T-Bone release was retracted due to an unexpected issue. 

Looking forward to hearing from you. For the procedure to be done, we can contact on private through mail (JRC-CO2MPAS@ec.europa.eu)

Regards,
Dimitris.
