### ISSUE TITLE
Datasync data field titles

### ISSUE THREAD

**Issue by MaikeruJon** [JRCSTU/CO2MPAS-TA#21]
After generating the template to be used for the datasync function, we have a workbook with three worksheets.
Looking at the 'dyno' worksheet. What is the data required in such as 'Dyno Engine Coolant Temperature [oC]'? This does not exist. No aspect of the dynamometer is recording engine coolant temperature. Or any other characteristic of the engine, for that matter. Shouldn't this be 'OBD Engine Coolant Temperature', and similarly for all other engine condition data?

**Comment by gfon** [comment]
@MaikeruJon  you don't have to provide any data to the Dyno Engine Coolant Temperature field. It is there rather for engineering purposes (in the beginning of the project before we decided to use OBD signals for ECT there was a discussion on how to measure engine coolant temperature externally).  

In any case the idea is to align OBD and dyno datasets and bring them to the same time reference so the signals provided in the dyno sheet do not have to completely match those of the obd sheet as long as there is one common signal between the two (vehicle speed).

**Comment by MaikeruJon** [comment]
OK, got it, thanks. So, having done that, the idea is to replace the original data (in the CO2MPAS input file) with the data from the datasync output and then run the CO2MPAS TA simulation, right?

**Comment by VictorValverde** [comment]
@MaikeruJon Yes that is correct.
To summarize:
1. Populate the datasync template with dyno and OBD series to be synchronized.
2. Synchronize with the datasync tool
3. Populate CO2MPAS input file with synched time-series
4. Run CO2MPAS simulation

**Comment by MaikeruJon** [comment]
OK, I've got it. Many thanks for your clear guidance.
