### ISSUE TITLE
Presentation Example

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/CO2MPAS-TA#3]
![graph_engine_temp](https://cloud.githubusercontent.com/assets/22169206/20601203/a4d9455e-b257-11e6-9798-9b61321c6ba8.png)

````
2016-11-23 22:26:29,459:co2mpas.io.schema:ERROR:
Input cannot be parsed, due to:
  ('initial_temperature', 'engine_coolant_temperatures', 'engine_speeds_out', 'idle_engine_speed_median') in input/calibration/wltp_h: Initial engine temperature outside permissible limits according to GTR!
````

**Comment by VictorValverde** [comment]
Example issue opened during CO2MPAS workshop

**Comment by ankostis** [comment]
Maybe @dimitriskomnos you can retrofit this issue as a prototype sample for submitting new issues.
