### ISSUE TITLE
Data restriction on Test mass

### ISSUE THREAD

**Issue by Steinbachson** [JRCSTU/CO2MPAS-TA#38]
Hello,

which data restriction is deposited for the cell with the test mass WLTP high and low?

Thanks for fast answer.

**Comment by dimitriskomnos** [comment]
Dear @Steinbachson, 

If I understand correctly, you refer to the restriction of the cell  `vehicle_mass WLTP-H/L` which does not allow you to insert a value greater than 3500 kg. 
Is this correct? 

To disable this restriction, please do the following in the Input file: 
1. Go to the spreadsheet: **Inputs**;
2. Select the tab _REVIEW_ on the top of the document;
3. There, you will find the option: _Unprotect Sheet_. Click on it;
4. Now select the cell(s) that you want to change/disable the restrictions;
5. Navigate to the tab _DATA_ and click on the _Data Validation_
6. A window will open. There:
   - Either click on the _Clear all_ button; 
   - Or change the permissible boundaries. 

We suggest the second option. These restrictions have been added to prevent major errors when inserting values, so by just disabling them, you should pay extra attention in the future. 

Let us know if the above actions answer your question, and solves the problem.
If yes, please comment and close the issue. 

Kind regards.

**Comment by Steinbachson** [comment]
Dear @dimitriskomnos,

thanks for the quick response. Your answer solved the problem.
I hope the simulation runs without problems regarding this change.


Kind regards and a huge thankyou!
