### ISSUE TITLE
Reporting of additional values for (N)OVC HEV

### ISSUE THREAD

**Issue by koglerp** [JRCSTU/CO2MPAS-TA#44]
Dear all,

according to the voted implementation of changes in the 2017/1153 Regulation (https://ec.europa.eu/transparency/regcomitology/index.cfm?do=search.documentdetail&Dos_ID=18305&DS_ID=64011&Version=2) there are a lot of new values requested for reporting. Do you know if there are any plans of handling this with a new inputfile, even if there is no CO2 Simulation needed for (N)OVC HEV? 

Best regards,
Patrick

**Comment by gfon** [comment]
Dear @koglerp,

Yes our team is modifying the co2mpas input file accordingly so the additional data can be communicated following the current process.  A new input file and a new co2mpas release will be provided soon.

Kindest regards,
Giorgos

**Comment by koglerp** [comment]
Thanks for your fast response!
