### ISSUE TITLE
PHEV UF WLTP-CO2 WEIGHTED VALUES

### ISSUE THREAD

**Issue by albertoleon86** [JRCSTU/CO2MPAS-TA#49]
Dear Sirs 

I have a question regarding the UF weighted WLTP-CO2 measured and declared for PHEV vehicles.

In the input file there's two rows 156 and 157.

The UF WLTP-CO2 weighted declared ( row 157) is the result of applying the formula from 2018/1832, point 4.1.3.2, that's fine.

But for the value that is required in the row 156 I cannot find it in the regulation 2018/1832!

Is this UF-WLTP-CO2 weighted measured the one that is stated in the regulation 2018/1840?

If not what value should we use in this row? And from which regulation?

Thanks in advance!

**Comment by sapofra** [comment]
Dear user,
the UF WLTP-CO2 weighted declared ( row 157) is the final UF-weighted declared value for this OVC IP family taken from entry 2.5.3.3 of the EC type-approval certificate (OVC-HEV only).
WLTP utility factor- weighted combined CO2 emission (measured) from raw 156 is described in regulation 2019/1840 and bellow:
![photo5929389969640633685](https://user-images.githubusercontent.com/29604134/110760765-554bf280-824f-11eb-8599-aba5f2631ba0.jpg)
 Co2mpas Team
