### ISSUE TITLE
Datasync destroys my hard drive

### ISSUE THREAD

**Issue by ankostis** [JRCSTU/CO2MPAS-TA#6]
When use the Datasyn tab of Co@MPAD GUI, my D: drives goes blank!

![image](https://cloud.githubusercontent.com/assets/501585/20625476/ea5469d0-b313-11e6-9800-54189ae2813a.png)

Also, when I'm simulating, the buttton doesn't work:
```
2016-11-25 12:34:46,154:tkui:ERROR:No inputs specified!  Please add files & folders in the Inputs list at the top-left.

```

**Comment by gfon** [comment]
Thank you for your feedback, We will come back to you on this soon.

**Comment by gfon** [comment]
Please @ankostis check that the synchronization of your data is correct. 
If this solution doesn't work for you please send us in co2mpas@jrc.ec.europa.eu your input file for further scrutiny.

**Comment by ankostis** [comment]
It's ok, thank you, I did, and it works now.

**Comment by ankostis** [comment]
@ciuffbi I owe you a Pizza.
