### ISSUE TITLE
Cannot use OpenOffice tool for reading output results

### ISSUE THREAD

**Issue by RAR-Melencu** [JRCSTU/CO2MPAS-TA#7]
![untitled](https://cloud.githubusercontent.com/assets/23739703/20625491/611a9adc-b31c-11e6-94f9-6aa082b88eb1.png)

**Comment by vinci1it2000** [comment]
With the new release is compatible. We are evaluating all excel formulas before saving the file. This has solved the compatibility issue.

Best,

Vincenzo Arcidiacono
